/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppChild {
        "p1": string;
        "p2": string;
    }
    interface AppHome {
    }
    interface AppNest {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppChildElement extends Components.AppChild, HTMLStencilElement {
    }
    var HTMLAppChildElement: {
        prototype: HTMLAppChildElement;
        new (): HTMLAppChildElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppNestElement extends Components.AppNest, HTMLStencilElement {
    }
    var HTMLAppNestElement: {
        prototype: HTMLAppNestElement;
        new (): HTMLAppNestElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-child": HTMLAppChildElement;
        "app-home": HTMLAppHomeElement;
        "app-nest": HTMLAppNestElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppChild {
        "p1"?: string;
        "p2"?: string;
    }
    interface AppHome {
    }
    interface AppNest {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-child": AppChild;
        "app-home": AppHome;
        "app-nest": AppNest;
        "app-profile": AppProfile;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-child": LocalJSX.AppChild & JSXBase.HTMLAttributes<HTMLAppChildElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-nest": LocalJSX.AppNest & JSXBase.HTMLAttributes<HTMLAppNestElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
